# Generated by Django 4.1.13 on 2023-11-22 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='time',
            field=models.TimeField(default=datetime.time(11, 22, 4, 610692)),
        ),
    ]
