# Generated by Django 4.1.13 on 2024-01-28 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_alter_movie_image_alter_seat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='time',
            field=models.TimeField(default=datetime.time(7, 45, 4, 112151)),
        ),
    ]
